# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.5

# Default target executed when no arguments are given to make.
default_target: all

.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:


#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:


# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list


# Suppress display of executed commands.
$(VERBOSE).SILENT:


# A target that is always out of date.
cmake_force:

.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/paulo/batch_segmentation

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/paulo/batch_segmentation

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake cache editor..."
	/usr/bin/ccmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache

.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache

.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/paulo/batch_segmentation/CMakeFiles /home/paulo/batch_segmentation/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/paulo/batch_segmentation/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean

.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named remove_similar_segm

# Build rule for target.
remove_similar_segm: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 remove_similar_segm
.PHONY : remove_similar_segm

# fast build rule for target.
remove_similar_segm/fast:
	$(MAKE) -f CMakeFiles/remove_similar_segm.dir/build.make CMakeFiles/remove_similar_segm.dir/build
.PHONY : remove_similar_segm/fast

#=============================================================================
# Target rules for targets named segment_meshes

# Build rule for target.
segment_meshes: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 segment_meshes
.PHONY : segment_meshes

# fast build rule for target.
segment_meshes/fast:
	$(MAKE) -f CMakeFiles/segment_meshes.dir/build.make CMakeFiles/segment_meshes.dir/build
.PHONY : segment_meshes/fast

remove_similar_segm.o: remove_similar_segm.cpp.o

.PHONY : remove_similar_segm.o

# target to build an object file
remove_similar_segm.cpp.o:
	$(MAKE) -f CMakeFiles/remove_similar_segm.dir/build.make CMakeFiles/remove_similar_segm.dir/remove_similar_segm.cpp.o
.PHONY : remove_similar_segm.cpp.o

remove_similar_segm.i: remove_similar_segm.cpp.i

.PHONY : remove_similar_segm.i

# target to preprocess a source file
remove_similar_segm.cpp.i:
	$(MAKE) -f CMakeFiles/remove_similar_segm.dir/build.make CMakeFiles/remove_similar_segm.dir/remove_similar_segm.cpp.i
.PHONY : remove_similar_segm.cpp.i

remove_similar_segm.s: remove_similar_segm.cpp.s

.PHONY : remove_similar_segm.s

# target to generate assembly for a file
remove_similar_segm.cpp.s:
	$(MAKE) -f CMakeFiles/remove_similar_segm.dir/build.make CMakeFiles/remove_similar_segm.dir/remove_similar_segm.cpp.s
.PHONY : remove_similar_segm.cpp.s

segment_meshes.o: segment_meshes.cpp.o

.PHONY : segment_meshes.o

# target to build an object file
segment_meshes.cpp.o:
	$(MAKE) -f CMakeFiles/segment_meshes.dir/build.make CMakeFiles/segment_meshes.dir/segment_meshes.cpp.o
.PHONY : segment_meshes.cpp.o

segment_meshes.i: segment_meshes.cpp.i

.PHONY : segment_meshes.i

# target to preprocess a source file
segment_meshes.cpp.i:
	$(MAKE) -f CMakeFiles/segment_meshes.dir/build.make CMakeFiles/segment_meshes.dir/segment_meshes.cpp.i
.PHONY : segment_meshes.cpp.i

segment_meshes.s: segment_meshes.cpp.s

.PHONY : segment_meshes.s

# target to generate assembly for a file
segment_meshes.cpp.s:
	$(MAKE) -f CMakeFiles/segment_meshes.dir/build.make CMakeFiles/segment_meshes.dir/segment_meshes.cpp.s
.PHONY : segment_meshes.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... remove_similar_segm"
	@echo "... segment_meshes"
	@echo "... remove_similar_segm.o"
	@echo "... remove_similar_segm.i"
	@echo "... remove_similar_segm.s"
	@echo "... segment_meshes.o"
	@echo "... segment_meshes.i"
	@echo "... segment_meshes.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

